
package vista;

import controlador.Controlador_FRM_MantenimientoEstudiantes;

public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;
    public FRM_MantenimientoEstudiantes() {
        initComponents();
        controlador_FRM_MantenimientoEstudiantes= new Controlador_FRM_MantenimientoEstudiantes(this);
        panel_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);   
    }

    public void establecerOpcionAlControlador(String opcion)
    {
       controlador_FRM_MantenimientoEstudiantes.setOpcion(opcion);
    }
    public  String[] devolverInformacionIngresada()
    {
        return this.panel_InformacionEstudiantes1.devolverInformacionIngresada();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.panel_InformacionEstudiantes1.mostrarInformacion(arreglo);
    }
    
    public void inicializarGUI()
    {
        panel_Botones1.inicializarGUI();
        panel_InformacionEstudiantes1.inicializarGUI();
    }
    
    public void habilitarAgregar()
    {
        panel_InformacionEstudiantes1.habilitarEdicion();
        panel_Botones1.habilitarAgregar();
        
    }
    
    public void habilitarEdicion()
    {
        panel_InformacionEstudiantes1.habilitarEdicion();
        panel_Botones1.habilitarEdicion();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Botones1 = new vista.Panel_Botones();
        panel_InformacionEstudiantes1 = new vista.Panel_InformacionEstudiantes();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Botones1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_InformacionEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_InformacionEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_Botones panel_Botones1;
    private vista.Panel_InformacionEstudiantes panel_InformacionEstudiantes1;
    // End of variables declaration//GEN-END:variables
}
