/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class Panel_InformacionCursos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Cursos
     */
    String arregloInformacionIngresada[]= new String[4];
    public Panel_InformacionCursos() {
        initComponents();
        llenarJCB();
    }

    public void inicializarGUI()
    {
        this.txtSiglas.setEnabled(true);
        this.txtSiglas.setText("");
        this.txtNombre.setEnabled(false);
        this.txtNombre.setText("");
        this.jcbCreditos.setEnabled(false);
        this.txtHorario.setEnabled(false);
        this.txtHorario.setText("");
    }
    
    public void habilitarEdicion()
    {
        this.txtSiglas.setEnabled(false);
        this.txtNombre.setEnabled(true);
        this.jcbCreditos.setEnabled(true);
        this.txtHorario.setEnabled(true);
    }
    
     public String[] devolverInformacion()
    {
        String informacion[]=new String[4];
        informacion[0]=this.txtSiglas.getText();
        informacion[1]=this.txtNombre.getText();
        informacion[2]=""+this.jcbCreditos.getSelectedIndex();
        informacion[3]=this.txtHorario.getText();
        
        return informacion;
    }
    
     public void mostrarInformacion(String arreglo[])
    {
        this.txtNombre.setText(arreglo[1]);
        this.jcbCreditos.setSelectedIndex(Integer.parseInt(arreglo[2]));
        this.txtHorario.setText(arreglo[3]);
        
    }
      public String[] devolverInformacionIngresada()
    {
        arregloInformacionIngresada[0]=txtSiglas.getText();
        arregloInformacionIngresada[1]=txtNombre.getText();
        arregloInformacionIngresada[2]=""+jcbCreditos.getSelectedIndex();
        arregloInformacionIngresada[3]=txtHorario.getText();
        
        return arregloInformacionIngresada;
    }
      public String devolverSigla()
    {
        return this.txtSiglas.getText();
    }
    public void llenarJCB()
    {
        int contador;
        this.jcbCreditos.removeAllItems();
        
        for(contador=0;contador<=50;contador++)
        {
            this.jcbCreditos.addItem(""+contador);
            
        }
        this.jcbCreditos.setSelectedIndex(4);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSiglas = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbCreditos = new javax.swing.JComboBox();

        jLabel3.setText("Creditos");

        jLabel4.setText("Horario");

        jLabel1.setText("Siglas");

        jLabel2.setText("Nombre");

        jcbCreditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSiglas)
                    .addComponent(txtNombre)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcbCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcbCreditos;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSiglas;
    // End of variables declaration//GEN-END:variables
}
